services:
  postgres:
    image: postgres:latest
    container_name: blog.api.pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - blog.api.network
    env_file:
      - .env

volumes:
  pg_data:

networks:
  blog.api.network:
    name: blog.api.network
    driver: bridge