services:
  postgres:
    profiles: ["api", "migrations", "test"]
    image: postgres:latest
    container_name: blog.api.pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - blog.api.network
    env_file:
      - .env

  redis:
    profiles: [ "api", "test" ]
    image: redis:latest
    container_name: blog.api.redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - blog.api.network
    env_file:
      - .env

  api:
    profiles: [ "api" ]
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - blog.api.network
    volumes:
      - ./src:/usr/api/src
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  migrations:
    profiles: [ "migrations" ]
    image: api_blog_test_task-api:latest
    container_name: api.pg.migrations
    environment:
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - blog.api.network
    command: ["uv", "run", "alembic", "upgrade", "head"]
    env_file:
      - .env

  test:
    profiles: [ "test" ]
    image: api_blog_test_task-api:latest
    container_name: api.test
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - blog.api.network
    command: ["uv", "run", "pytest", "tests/test_cache_api.py", "-v"]
    env_file:
      - .env

volumes:
  pg_data:
  redis_data:

networks:
  blog.api.network:
    name: blog.api.network
    driver: bridge